from fpdf import FPDF
from fpdf.enums import XPos, YPos
from datetime import datetime


class VerityPDFReport(FPDF):

    def header(self):
        # Draw background header block
        self.set_fill_color(83, 74, 183)  # #534AB7 theme color
        self.rect(0, 0, 210, 30, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 14)
        # Margin offsets
        self.set_y(8)
        self.cell(0, 6, "VERITY CLAIM VERIFICATION REPORT", border=False, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="L")
        self.set_font("Helvetica", "I", 9)
        self.cell(0, 4, "Hallucination & Citation Verification Analysis", border=False, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="L")
        self.set_y(35)  # Reset Y position below header banner

    def footer(self):
        self.set_y(-15)
        self.set_text_color(150, 150, 150)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Verity RAG Verifier", border=0, align="C")


def generate_verification_pdf(run) -> bytes:
    pdf = VerityPDFReport()
    pdf.set_margins(15, 35, 15)
    pdf.add_page()

    # Reset text color
    pdf.set_text_color(50, 50, 50)
    pdf.ln(5)

    # Title summary
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Run Summary: Run #{run.id}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)

    date_str = run.created_at.strftime("%Y-%m-%d %H:%M:%S") if run.created_at else "Unknown"
    pdf.cell(90, 6, f"Date: {date_str}")
    pdf.cell(90, 6, f"LLM Provider: {run.provider.upper()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # Stats row
    stats = run.stats
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(45, 8, "Total Claims", border=1, align="C", fill=True)
    pdf.cell(45, 8, "Supported", border=1, align="C", fill=True)
    pdf.cell(45, 8, "Contradicted", border=1, align="C", fill=True)
    pdf.cell(45, 8, "Unsupported", border=1, align="C", fill=True)
    pdf.ln(8)

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(45, 8, str(stats.get("total", 0)), border=1, align="C")
    pdf.cell(45, 8, str(stats.get("supported", 0)), border=1, align="C")
    pdf.cell(45, 8, str(stats.get("contradicted", 0)), border=1, align="C")
    pdf.cell(45, 8, str(stats.get("unsupported", 0)), border=1, align="C")
    pdf.ln(12)

    # Checked Answer
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Checked Answer Text:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5, run.answer, border=1)
    pdf.ln(8)

    # Claims breakdown
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Claim-by-Claim Breakdown:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    for i, claim_item in enumerate(run.claims, 1):
        pdf.set_font("Helvetica", "B", 10)
        label = claim_item.get("label", "unsupported").upper()

        # Set color based on label
        if label == "SUPPORTED":
            pdf.set_text_color(39, 80, 10)  # Dark green
        elif label == "CONTRADICTED":
            pdf.set_text_color(121, 31, 31)  # Dark red
        else:
            pdf.set_text_color(99, 56, 6)  # Dark gold

        pdf.cell(0, 6, f"Claim {i}: {claim_item.get('claim')} [{label}]", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(50, 50, 50)

        # Evidence
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, "Evidence:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 9)
        evidence = claim_item.get("evidence", "")
        if not evidence:
            evidence = "No evidence found in source."
        pdf.multi_cell(0, 5, evidence)
        pdf.ln(1)

        # Reasoning
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, "Reasoning:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, claim_item.get("reasoning", ""))
        pdf.ln(4)

    return bytes(pdf.output())
